## This file defines the configuration for odss2dash.

## To get platform and position information:
odssApi = "https://odss.mbari.org/odss"

## Server port to listen for requests:
port = 3033

## External URL of the odss2dash service
externalUrl = "http://localhost:3033"
#externalUrl = "https://okeanids.mbari.org/odss2dash"

## Interval to perform the dispatch:
pollPeriod = "30 seconds"

## Default limit for positions request against ODSS API:
defaultLastNumberOfFixes = 5

## Target TethysDash instances:
## For each:
##  `name`: A simple, alphanumeric string
##  `api`: The TehysDash API endpoint
##  `apiKey`: Use `$EV` syntax to indicate environment variable with the key.
##            A local `.env` file can be used to capture such variables.
[[tethysdashes]]
name = "okeanids"
api = "https://okeanids.mbari.org/TethysDash/api"
apiKey = "$OKEANIDS_APIKEY"

[[tethysdashes]]
name = "tethystest"
api = "http://tethystest.shore.mbari.org:8080/TethysDash/api"
apiKey = "$TETHYSTEST_APIKEY"
