# Basis for actual spec on production server.

version: '3.7'
services:
  odss2dash:
    container_name: odss2dash
    image: mbari/odss2dash:2
    ports:
      - '3033:3033'
    volumes:
      - $PWD/odss2dash:/public

    environment:
      - OKEANIDS_APIKEY
      - TETHYSTEST_APIKEY
      - RUST_LOG=info
      - RUST_BACKTRACE=0

    command: serve

    ## for any immediate initial notifications:
    depends_on:
      - tethysdash

    init: true
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
